spring:
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/Diagnostico}
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
api:
  url: https://dog-api.kinduff.com/api/facts
server:
  port: 8081