POST http://localhost:8081/api/v1/pet
Content-Type: application/json

{
    "name": "Equis de",
    "birthdate": "2020-05-15",
    "breed": "labrador",
    "status": true
}

###

GET http://localhost:8081/api/v1/pet

###

PUT http://localhost:8081/api/v1/pet/2